### ISSUE TITLE
API call to https://cis.schibsted.com/api/v1/identify is blocked by browser

### ISSUE THREAD

**Issue by main-sonn** [schibsted/WAAS#153]
### Provide environment information

Firefox: 112.0.2

### To Reproduce

Open the network analysis of firefox browser. the api call is blocked:

### Describe the Bug

![Screenshot_20230503_113840](https://user-images.githubusercontent.com/63794020/235882623-868073f5-8190-45a0-90ea-dd9b66cd7c78.png)

### Expected Behavior

What does this api call? If this api call isn't necessary, could it be removed?

**Comment by Johannes-Andersen** [comment]
This is related to #105 :)
The blocked request is coming from Firefox built-in tracking protection.

Since we use it internally in Schibsted we wanted some basic tracking to know if people were using it or not.
So we would love for anyone to contribute to #105, but it is also on the radar for the frontend re-write I am trying to do in #215
